function openKitten(k=null){const current=k?isCurrentFoster(k):true;showSheet(k?'Edit kitten':'Add kitten',`<form id="kittenForm" class="form-grid"><div class="profile-photo-wrap"><div class="photo-preview" id="photoPreview">${k?.photo?`<img src="${k.photo}">`:'🐱'}</div><div style="flex:1">${k?`<div class="photo-help"><b>Profile picture</b><br>To change or remove this photo, save your changes and tap the kitten's picture on their profile.</div>`:`<div class="field"><label>Profile picture</label><input type="file" id="photoInput" accept="image/*"></div><div class="photo-help">Choose an existing photo or take a new one. You can crop and position it before saving.</div>`}</div></div>
 <div class="field"><label>Name *</label><input name="name" required value="${esc(k?.name||'')}"></div>
 <div class="identity-grid"><div class="field"><label>Litter</label><select name="litterId"><option value="">Unassigned</option>${state.litters.map(l=>`<option value="${l.id}" ${k?.litterId===l.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select></div><div class="field"><label>Currently in your foster care?</label><select name="inFosterCare"><option value="yes" ${current?'selected':''}>Yes</option><option value="no" ${!current?'selected':''}>No</option></select></div></div>
 <div class="info">Choose <b>No</b> when this kitten is no longer in your care. The kitten will leave your active foster list, but their profile and full care history will stay under Foster history.</div>
 <div class="identity-grid"><div class="field"><label>Date of birth (override)</label><input type="date" name="dob" value="${k?.dob||''}"></div><div class="field"><label>Sex</label><select name="sex"><option value="">Unknown</option><option ${k?.sex==='Female'?'selected':''}>Female</option><option ${k?.sex==='Male'?'selected':''}>Male</option></select></div></div>
 <div class="field"><label>Color / markings</label><input name="markings" value="${esc(k?.markings||'')}"></div>
 <div class="field"><label>Special needs / medical notes</label><textarea name="specialNeeds">${esc(k?.specialNeeds||'')}</textarea></div>
 <div class="field"><label>Feed every (hours)</label><input type="number" min="1" max="24" step="0.5" name="feedingIntervalHours" value="${k?.feedingIntervalHours||4}"></div>
 <div class="info">Shelterluv remains the source of truth for intake date, Shelter ID, microchip, and official intake weight. After saving, use <b>Weight</b> to log the kitten's current weight in this app.</div>
 <label class="field-check"><input type="checkbox" name="feedingEnabled" ${k?.carePlan?.feedingEnabled===false?'':'checked'}> Timed feeding reminders enabled</label><label class="field-check"><input type="checkbox" name="dailyWeight" ${k?.carePlan?.dailyWeight===false?'':'checked'}> Daily weight reminder enabled</label><label class="field-check"><input type="checkbox" name="bottleBaby" ${k?.carePlan?.bottleBaby?'checked':''}> Bottle Baby Mode (emphasize feeds, weights, potty)</label>
 <div class="sheet-actions"><button type="button" class="btn secondary" id="cancelForm">Cancel</button><button class="btn primary">Save kitten</button></div>${k?`<div class="danger-zone"><button type="button" class="btn danger" id="deleteKitten">Permanently remove kitten & logs</button></div>`:''}</form>`);
 let photo=k?.photo||null;if($('#photoInput'))$('#photoInput').onchange=e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;openPhotoCropper(file,cropped=>{photo=cropped;$('#photoPreview').innerHTML=`<img src="${photo}">`})};$('#cancelForm').onclick=closeSheet;
 $('#kittenForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),interval=Number(f.get('feedingIntervalHours'))||4,inFosterCare=f.get('inFosterCare')==='yes';const id=k?.id||uid('kitten'),obj={...(k||{}),id,name:String(f.get('name')).trim(),litterId:f.get('litterId')||null,inFosterCare,status:k?.status||'In foster',dob:f.get('dob'),sex:f.get('sex'),markings:String(f.get('markings')).trim(),specialNeeds:String(f.get('specialNeeds')).trim(),feedingIntervalHours:interval,medications:k?.medications||[],photo,carePlan:{feedingEnabled:f.get('feedingEnabled')==='on',dailyWeight:f.get('dailyWeight')==='on',bottleBaby:f.get('bottleBaby')==='on'}};if(k)Object.assign(k,obj);else state.kittens.push(obj);save();closeSheet();if(inFosterCare){activeKittenId=id;activeView='profile';render();toast(k?'Kitten updated':'Kitten added')}else{activeKittenId=null;activeView='kittens';render();toast(`${obj.name} moved to Foster history`)}};if(k)$('#deleteKitten').onclick=()=>{if(confirm(`Permanently remove ${k.name} and all local care logs? This cannot be undone.`)){state.kittens=state.kittens.filter(x=>x.id!==k.id);state.events=state.events.filter(x=>x.kittenId!==k.id);save();closeSheet();activeView='kittens';render();toast('Kitten permanently removed')}}}
function scheduleFields(m){const s=m?.schedule||{type:'daily',times:['08:00']},type=s.type||'daily';return `<div class="field"><label>Frequency</label><select name="scheduleType" id="scheduleType"><option value="daily" ${type==='daily'?'selected':''}>Once daily</option><option value="twiceDaily" ${type==='twiceDaily'?'selected':''}>Twice daily</option><option value="threeDaily" ${type==='threeDaily'?'selected':''}>Three times daily</option><option value="intervalHours" ${type==='intervalHours'?'selected':''}>Every X hours</option><option value="intervalDays" ${type==='intervalDays'?'selected':''}>Every X days</option><option value="specificDays" ${type==='specificDays'?'selected':''}>Specific days of week</option><option value="oneTime" ${type==='oneTime'?'selected':''}>One-time dose</option><option value="prn" ${type==='prn'?'selected':''}>As needed (PRN)</option></select></div><div id="scheduleExtra"></div>`}
